jwt:
  secret: secret

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/token_db
    username: root
    password: letmein
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

  trace:
    http:
      enabled: true

  endpoint:
    health:
      show-details: always
      sensitive: false
      probes:
        enabled: true


