jwt:
  secret: secret

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: letmein
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: backend
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-server: localhost:9092
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer



  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

  trace:
    http:
      enabled: true

  endpoint:
    health:
      show-details: always
      sensitive: false
      probes:
        enabled: true


